// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzyxbayetuxkxrikzcwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6eXhiYXlldHV4a3hyaWt6Y3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzE3MDcsImV4cCI6MjA3MTAwNzcwN30.0B9R6O1CsYXpr2emkWxDtEdZapstTgVIxeBL9jipEmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});